## Autograd
Autograd is now a core torch package for automatic differentiation. 

In [ ]:
import torch

In [ ]:
x = torch.tensor([[1., 1.], [2., 2.]], requires_grad=True)
print(x)



tensor([[1., 1.],
        [2., 2.]], requires_grad=True)


In [ ]:
y = x*x
print(y)

z = y.sum()

print(z)

tensor([[1., 1.],
        [4., 4.]], grad_fn=<MulBackward0>)
tensor(10., grad_fn=<SumBackward0>)


In [ ]:

z.backward()
print(x.grad)

tensor([[2., 2.],
        [4., 4.]])


## Let us see another example

In [ ]:
a = torch.tensor([1., 2.], requires_grad=True)
b = torch.tensor([3., 4.], requires_grad=True)

In [ ]:
Q = 2*a**3 - b**2
print(Q)

tensor([-7.,  0.], grad_fn=<SubBackward0>)


If output is a scalar, we can just call $.backward$.  Since Q is a vector, we need to pass gradient argument, which  is a tensor of the same shape as Q. It represents the gradient of Q w.r.t. itself.

In [ ]:
e_grad = torch.tensor([1., 1.])
Q.backward(gradient=e_grad)

In [ ]:
print(a.grad, b.grad)

tensor([ 6., 24.]) tensor([-6., -8.])
